name: Cross-Compile C for PYNQ-Z2

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        apt install --yes {gcc,binutils}-arm-linux-gnueabihf

    - name: Cross-Compile
      run: |
        arm-linux-gnueabihf-gcc -o out.exe main.c

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-artifacts
        path: out.exe

    - name: Save Compiled Binary Path
      id: binary-path
      run: echo "::set-output name=binary_path::out.exe"
